---
# HAProxy is not included in debian 10, but is in debian 11. buster-backports gives us access to debian 11 packages.
- name: Add buster-backports repository into sources list for HAProxy
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    update_cache: yes

- name: install haproxy
  become: yes
  apt:
    name: haproxy

# generate config from vars and start/restart the config
- name: load config
  become: yes
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0664"
  notify: "restart haproxy"

# place haproxy https cert
- name: write certificate if provided
  become: yes
  template:
    src: haproxy_cert.pem.j2
    dest: /etc/haproxy/haproxy_cert.pem
    owner: root
    group: root
    mode: "0660"
  notify: "restart haproxy"